ALTER TABLE RESERVATION
ADD CONSTRAINT fk1_RESERVATION FOREIGN KEY(id_membre) REFERENCES UTILISATEUR(id_membre);

ALTER TABLE PLACE 
ADD CONSTRAINT fk2_PLACE FOREIGN KEY(id_reserv) REFERENCES RESERVATION(id_reserv);

ALTER TABLE ATTENTE
ADD CONSTRAINT fk3_ATTENTE FOREIGN KEY(id_membre) REFERENCES UTILISATEUR(id_membre);