ALTER TABLE PLACE
ADD CONSTRAINT fk1_PLACE FOREIGN KEY(id_place) REFERENCES RESERVATION(id_reserv);

ALTER TABLE RESERVATION 
ADD CONSTRAINT fk2_RESERVATION FOREIGN KEY(id_reserv) REFERENCES MEMBRE(id_membre);

ALTER TABLE ATTENTE
ADD CONSTRAINT fk3_ATTENTE FOREIGN KEY(id_attente) REFERENCES MEMBRE(id_membre);